### ISSUE TITLE
[Feature] Stats Display in Lobby

### ISSUE THREAD

**Issue by unaussprechlich** [unaussprechlich/warlordsplus#41]
People want to know how good they are :)

- [x]  add general stats in lobby
- [x]  add individual stats above gamemodes
- [x]  add individual stats above classes

**Comment by ebicep** [comment]
solo added

**Comment by unaussprechlich** [comment]
Looks ugly tho

**Comment by ebicep** [comment]
> Looks ugly tho

You're ugly

**Comment by ebicep** [comment]
GOOD ENOUGH
